format = """
[î‚¶](#F02E6E)\
$directory\
[î‚´ ](#F02E6E)\
[î‚¶](#F48FB1)\
$git_branch\
$git_status\
[î‚´ ](#F48FB1)\
[î‚¶](#3E3859)\
$c\
$deno\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
[î‚´ ](#3E3859)\
$cmd_duration
$character
"""

[cmd_duration]
show_milliseconds = true
min_time = 1_000
style = 'fg:#DCDFE4'
format = '[$duration]($style)'

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"

[aws]
symbol = "îŒ½  "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[buf]
symbol = "ï’ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[c]
symbol = "î˜ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[conda]
symbol = "ï„Œ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[dart]
symbol = "î˜ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[deno]
# symbol = " "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'
detect_extensions = []

[directory]
style = "fg:#100E23 bg:#F02E6E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " ï ½"

[docker_context]
symbol = "ïŒˆ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[elixir]
symbol = "î‰µ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[fossil_branch]
symbol = "ï˜ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "fg:#100E23 bg:#F48FB1"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#100E23 bg:#F48FB1"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[guix_shell]
symbol = "ïŒ¥ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[haxe]
symbol = "âŒ˜ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[hg_branch]
symbol = "ï˜ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[lua]
symbol = "î˜  "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[memory_usage]
symbol = "ï¡š "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[meson]
symbol = "ï¨¶ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[nix_shell]
symbol = "ïŒ“ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = "îœ˜ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'
detect_extensions = []

[package]
symbol = "ï£– "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[pijul_channel]
symbol = "ğŸªº "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[python]
symbol = "îˆµ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[rlang]
symbol = "ï³’ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[ruby]
symbol = "î‘ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#3E3859"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'

[spack]
symbol = "ğŸ…¢ "
style = "bg:#3E3859"
format = '[ $symbol($version) ]($style)'
